---

- name: Remove previous docker installation
  yum:
    name: "{{ item.package }}"
    state: absent
  with_items: "{{ docker_cleanup_packages_rhel }}"
  tags: cleanup

- name: Import Docker CE repo gpg key
  rpm_key:
    key: https://download.docker.com/linux/centos/gpg
    state: present

- name: Add docker-ce repo
  get_url:
    url: https://download.docker.com/linux/centos/docker-ce.repo
    dest: /etc/yum.repos.d/docker-ce.repo
    force: yes
    owner: root
    group: root
    mode: 0644

- name: Install Docker-CE
  yum: name=docker-ce state=latest update_cache=yes

- name: create user docker_user
  user:
    name: docker_user
    group: docker
    createhome: yes
    password: user$docker$

- name: Create dir for docker proxy settings
  file:
    path: /etc/systemd/system/docker.service.d 
    state: directory

- name: Create file for proxy settings for docker containers
  blockinfile:
    create: yes     
    dest: /etc/systemd/system/docker.service.d/http-proxy.conf
    content: |
      [Service]
      Environment="HTTP_PROXY=http://146.108.8.18:3128"
      Environment="HTTPS_PROXY=https://146.108.8.18:3128"
  notify: reload systemd
