---
# tasks file for docker-ce ansible role

- name: Install docker-ce on RHEL/CentOS
  include: install-rhel.yml
  when: ansible_os_family == 'RedHat'

- name: Install docker-ce on Ubuntu
  include: install-ubuntu.yml
  when: ansible_distribution == 'Ubuntu'

- name: Enable Docker CE service on startup
  service:
    name: docker
    state: started
    enabled: yes
